# Generated by Django 5.1.1 on 2025-05-30 09:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_alter_student_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='course',
            field=models.CharField(choices=[('BSEd', 'Bachelor of Secondary Education'), ('BSBM', 'Bachelor of Science in Business Management'), ('BSCS', 'Bachelor of Science in Computer Science'), ('BSCrim', 'Bachelor of Science in Criminology'), ('BSHM', 'Bachelor of Science in Hospitality Management'), ('BSIT', 'Bachelor of Science in Information Technology'), ('BSPsy', 'Bachelor of Science in Psychology')], default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Course',
        ),
    ]
