# Generated by Django 5.1.1 on 2025-06-01 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_course_remove_enrollment_date_enrolled_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('Regular', 'Regular'), ('Irregular', 'Irregular')], max_length=10),
        ),
    ]
