# Generated by Django 5.1.1 on 2025-06-02 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0007_remove_student_course_remove_student_nationality_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Course',
        ),
    ]
