# Generated by Django 5.1.1 on 2025-06-03 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0009_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='absent_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Attendance',
        ),
    ]
