# Generated by Django 5.1.1 on 2025-06-03 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0010_student_absent_count_delete_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='present_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
