# Generated by Django 5.1.1 on 2025-06-04 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0012_alter_grade_enrollment_exam_grade_exam_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='exam_status',
            field=models.CharField(choices=[('Done', 'Done'), ('Not Done', 'Not Done')], default='Not Done', max_length=10),
        ),
    ]
