# Generated by Django 5.1.1 on 2025-06-06 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0013_grade_exam_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grade',
            name='exam_status',
        ),
        migrations.AddField(
            model_name='grade',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
